services: 
    database:
        container_name: mysql
        ports:
            - "3306:3306"
        expose: ["3306"]
    scadalts:
        container_name: scadalts
        ports: 
            - "8080:8080"
        expose: ["8080", "8000"]
    opcuaserver:
        container_name: opcuaserver
        ports:
          - 4840:4840
        expose: ["4840"]

