services: 
    database:
        extends:
            file: compose-base.yml
            service: database
        container_name: mysql-test
        ports:
            - "3307:3306"
        volumes:
            - /volumes/test/database/data:/var/lib/mysql:rw
            - /volumes/test/database/config:/etc/mysql:ro

    scadalts:
        extends:
            file: compose-base.yml
            service: scadalts
        container_name: scadalts-test
        ports: 
            - "8081:8080"
        links:
            - database:database
        depends_on:
            opcuaserver:
              condition: service_healthy
            database:
              condition: service_healthy
        volumes:
            - /volumes/test/webserver:/usr/local/tomcat:rw

    opcuaserver:
        extends:
            file: compose-base.yml
            service: opcuaserver
        container_name: opcuaserver-test
        ports:
            - "4841:4840"

