services: 
    database:
        extends:
            file: compose-base.yml
            service: database
        container_name: mysql-prod
        ports:
            - "3306:3306"
        volumes:
            - /volumes/test/database/data:/var/lib/mysql:rw
            - /volumes/test/database/config:/etc/mysql:ro

    argos:
        extends:
            file: compose-base.yml
            service: argos
        container_name: argos-prod
        ports:
            - "8080:8080"
        links:
            - database:database
        depends_on:
            opcuaserver:
              condition: service_healthy
            database:
              condition: service_healthy

    opcuaserver:
        extends:
            file: compose-base.yml
            service: opcuaserver
        container_name: opcuaserver-prod
        ports:
            - "4840:4840"

