services: 
    database:
        extends:
            file: compose-base.yml
            service: database
        container_name: mysql-prod
        ports:
            - "3306:3306"
        expose: ["3306"]

    argos:
        extends:
            file: compose-base.yml
            service: argos
        container_name: argos-prod
        links:
            - database:database
        depends_on:
            opcuaserver:
              condition: service_healthy
            database:
              condition: service_healthy
        ports: 
            - "8080:8080"
        expose: ["8080", "8000"]
        volumes:
            - ./volumes/prod/tomcat:/usr/local/tomcat:rw

    opcuaserver:
        extends:
            file: compose-base.yml
            service: opcuaserver
        container_name: opcuaserver-prod
        ports:
            - "4840:4840"
        expose: ["4840"]

