services: 
    database:
        container_name: mysql
        image: mysql/mysql-server:8.0.32
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        volumes:
            - ./volumes/database/data:/var/lib/mysql:rw
            - ./volumes/database/config:/etc/mysql:ro
        command: --log_bin_trust_function_creators=1
        deploy:
          resources:
            limits:
             cpus: '1'
             memory: 768M
        healthcheck:
          test: mysqladmin ping -h localhost
          interval: 5s
          timeout: 10s
          retries: 10
          start_period: 5s
          start_interval: 5s

    scadalts:
        container_name: scadalts
        image: scadalts:latest
        build:
          context: .
          dockerfile: Dockerfile
          target: war_deploy
        environment:
            - CATALINA_OPTS=-Xmx512m -Xms512m
        volumes:
            - ./volumes/tomcat:/usr/local/tomcat:rw
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 1.2G

    opcuaserver:
        container_name: opcuaserver
        image: opcua_server:latest
        build: ./opcua_server
        healthcheck:
          test: echo "exit()" | uaclient -u localhost:4840
          interval: 5s
          timeout: 10s
          retries: 10
          start_period: 3s
        deploy:
          resources:
            limits:
              cpus: '1'
              memory: 128M

