# Docker compose file to manage your deployed images.
# Use MySQL server 5.7 and latest Scada-LTS local build.
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
version: '3'
services: 
    database:
        container_name: mysql
        image: mysql/mysql-server:8.0.32
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            - ./volumes/database/data:/var/lib/mysql:rw
            - ./volumes/database/config:/etc/mysql:ro
        command: --log_bin_trust_function_creators=1
        healthcheck:
          test: mysqladmin ping -h localhost
          interval: 5s
          timeout: 10s
          retries: 10
          start_period: 5s
          start_interval: 5s
    scadalts:
        container_name: scadalts
        image: scadalts:latest
        build:
          context: .
          dockerfile: Dockerfile
          target: war_deploy
        environment:
            - CATALINA_OPTS=-Xmx512m -Xms512m
        ports: 
            - "8080:8080"
        depends_on: 
            database:
              condition: service_healthy
        expose: ["8080", "8000"]
        volumes:
            - ./volumes/tomcat_log:/usr/local/tomcat/logs:rw
        links:
            - database:database

