# Docker compose file to manage your deployed images.
# Use MySQL server 5.7 and latest Scada-LTS local build.
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
version: '3'
services: 
    database:
        container_name: mysql-test
        ports:
            - "3307:3306"
    scadalts:
        container_name: scadalts-test
        ports: 
            - "8081:8080"
    opcuaserver:
        container_name: opcuaserver-test
        ports:
          - 4841:4840

