openapi: 3.0.0
servers:
  - url: 'http://localhost:8080/ScadaBR/api'
    description: 'Scada development Server'
    variables: {}
info:
  version: 2.6.0
  title: Scada-LTS API
  description: 'Scada-LTS OpenAPI Specification. Description contains only a SMS and Email new feature REST API'
  termsOfService: ''
  contact:
    name: 'Kamil Jarmusik - SoftQ Developer'
    email: 'kamil.jarmusik@softq.pl'
  license:
    name: 'GPL-2.0'
paths:
  /threads/states/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Get all states'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
  /threads/states/state/{state}/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Get threads from threads'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
      parameters:
        - name: 'state'
          in: 'path'
          required: true
          schema:
            type: 'string'
  /threads/states/state/{state}/count/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Get all stacks from threads'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
      parameters:
        - name: 'state'
          in: 'path'
          required: true
          schema:
            type: 'string'
  /threads/states/state/{state}/class/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Get all stacks from threads'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
      parameters:
        - name: 'state'
          in: 'path'
          required: true
          schema:
            type: 'string'
  /threads/states/state/{state}/name/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Get all stacks from threads'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
      parameters:
        - name: 'state'
          in: 'path'
          required: true
          schema:
            type: 'string'
  /threads/states/group-by/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Group stacks by thread then classes'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
  /threads/states/group-by/count/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Group stacks by thread then count'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
  /threads/states/group-by/class/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Group stacks by thread then names'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
  /threads/states/group-by/name/:
    get:
      tags:
        - ThreadInfoAPI
      description: 'Group threads by stack'
      responses:
        '200':
          description: 'Get successful'
          headers: { }
